// Code generated by entc, DO NOT EDIT.

package orderfield

const (
	// Label holds the string label denoting the orderfield type in the database.
	Label = "order_field"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"

	// EdgeMenu holds the string denoting the menu edge name in mutations.
	EdgeMenu = "menu"

	// Table holds the table name of the orderfield in the database.
	Table = "order_fields"
	// MenuTable is the table the holds the menu relation/edge.
	MenuTable = "menus"
	// MenuInverseTable is the table name for the Menu entity.
	// It exists in this package in order to avoid circular dependency with the "menu" package.
	MenuInverseTable = "menus"
	// MenuColumn is the table column denoting the menu relation/edge.
	MenuColumn = "order_field_menu"
)

// Columns holds all SQL columns for orderfield fields.
var Columns = []string{
	FieldID,
	FieldCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the OrderField type.
var ForeignKeys = []string{
	"order_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CountValidator is a validator for the "count" field. It is called by the builders before save.
	CountValidator func(uint16) error
)
