// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Server.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestaurantStatistics struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantStatistics) Reset()         { *m = RestaurantStatistics{} }
func (m *RestaurantStatistics) String() string { return proto.CompactTextString(m) }
func (*RestaurantStatistics) ProtoMessage()    {}
func (*RestaurantStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{0}
}

func (m *RestaurantStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantStatistics.Unmarshal(m, b)
}
func (m *RestaurantStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantStatistics.Marshal(b, m, deterministic)
}
func (m *RestaurantStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantStatistics.Merge(m, src)
}
func (m *RestaurantStatistics) XXX_Size() int {
	return xxx_messageInfo_RestaurantStatistics.Size(m)
}
func (m *RestaurantStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantStatistics proto.InternalMessageInfo

func (m *RestaurantStatistics) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Restaurant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubName              string   `protobuf:"bytes,2,opt,name=subName,proto3" json:"subName,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Root                 string   `protobuf:"bytes,9,opt,name=root,proto3" json:"root,omitempty"`
	Parent               string   `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	Children             []string `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{1}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetSubName() string {
	if m != nil {
		return m.SubName
	}
	return ""
}

func (m *Restaurant) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Restaurant) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Restaurant) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Restaurant) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

type Menus struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Menus                []*Menu  `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menus) Reset()         { *m = Menus{} }
func (m *Menus) String() string { return proto.CompactTextString(m) }
func (*Menus) ProtoMessage()    {}
func (*Menus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{2}
}

func (m *Menus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menus.Unmarshal(m, b)
}
func (m *Menus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menus.Marshal(b, m, deterministic)
}
func (m *Menus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menus.Merge(m, src)
}
func (m *Menus) XXX_Size() int {
	return xxx_messageInfo_Menus.Size(m)
}
func (m *Menus) XXX_DiscardUnknown() {
	xxx_messageInfo_Menus.DiscardUnknown(m)
}

var xxx_messageInfo_Menus proto.InternalMessageInfo

func (m *Menus) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Menus) GetMenus() []*Menu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type Menu struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceAmount          int64    `protobuf:"varint,4,opt,name=priceAmount,proto3" json:"priceAmount,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Owner                string   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Options              []*Menu  `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{3}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Menu) GetPriceAmount() int64 {
	if m != nil {
		return m.PriceAmount
	}
	return 0
}

func (m *Menu) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Menu) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Menu) GetOptions() []*Menu {
	if m != nil {
		return m.Options
	}
	return nil
}

type Auth struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{4}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Auth) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type User struct {
	Auth                 *Auth    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mime                 string   `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	CreateAt             string   `protobuf:"bytes,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{6}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *File) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type OrderField struct {
	Menu                 int64    `protobuf:"varint,1,opt,name=menu,proto3" json:"menu,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderField) Reset()         { *m = OrderField{} }
func (m *OrderField) String() string { return proto.CompactTextString(m) }
func (*OrderField) ProtoMessage()    {}
func (*OrderField) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{7}
}

func (m *OrderField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderField.Unmarshal(m, b)
}
func (m *OrderField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderField.Marshal(b, m, deterministic)
}
func (m *OrderField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderField.Merge(m, src)
}
func (m *OrderField) XXX_Size() int {
	return xxx_messageInfo_OrderField.Size(m)
}
func (m *OrderField) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderField.DiscardUnknown(m)
}

var xxx_messageInfo_OrderField proto.InternalMessageInfo

func (m *OrderField) GetMenu() int64 {
	if m != nil {
		return m.Menu
	}
	return 0
}

func (m *OrderField) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Order struct {
	Fields               []*OrderField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d447f7a82efed94, []int{8}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetFields() []*OrderField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*RestaurantStatistics)(nil), "pb.RestaurantStatistics")
	proto.RegisterType((*Restaurant)(nil), "pb.Restaurant")
	proto.RegisterType((*Menus)(nil), "pb.Menus")
	proto.RegisterType((*Menu)(nil), "pb.Menu")
	proto.RegisterType((*Auth)(nil), "pb.Auth")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*OrderField)(nil), "pb.OrderField")
	proto.RegisterType((*Order)(nil), "pb.Order")
}

func init() {
	proto.RegisterFile("Server.proto", fileDescriptor_7d447f7a82efed94)
}

var fileDescriptor_7d447f7a82efed94 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xb6, 0x9c, 0xc4, 0xb3, 0xcb, 0x52, 0xc4, 0x52, 0x44, 0xbf, 0x08, 0x3a, 0x94, 0x1c,
	0x4a, 0x0a, 0x2d, 0xf4, 0xd6, 0x43, 0x2e, 0x0b, 0x3d, 0xb4, 0x05, 0x2f, 0x3d, 0x96, 0xc5, 0xb1,
	0xa6, 0x44, 0x90, 0x58, 0x66, 0x24, 0xa7, 0xf4, 0x7f, 0xf4, 0x27, 0xf5, 0x87, 0x15, 0x8d, 0x15,
	0x27, 0x2c, 0x7b, 0x9b, 0xf7, 0xa4, 0xf7, 0xac, 0x37, 0x33, 0x86, 0xeb, 0x7b, 0xa4, 0x23, 0xd2,
	0xba, 0x27, 0x17, 0x9c, 0xcc, 0xfb, 0xad, 0x7e, 0x07, 0xb7, 0x35, 0xfa, 0xd0, 0x0c, 0xd4, 0x74,
	0xe1, 0x3e, 0x34, 0xc1, 0xfa, 0x60, 0x5b, 0x2f, 0x6f, 0xa1, 0xec, 0x9a, 0x03, 0x7a, 0x95, 0x2d,
	0x8b, 0x55, 0x55, 0x8f, 0x40, 0xff, 0xcd, 0x00, 0xce, 0xd7, 0xa5, 0x04, 0x11, 0x79, 0x95, 0x2d,
	0xb3, 0x55, 0x55, 0x73, 0x2d, 0x15, 0xcc, 0xfd, 0xb0, 0xfd, 0x16, 0xe9, 0x9c, 0xe9, 0x13, 0x94,
	0xcf, 0xa0, 0x18, 0x68, 0xaf, 0x0a, 0x66, 0x63, 0x19, 0xf5, 0xe4, 0x5c, 0x50, 0xd5, 0xa8, 0x8f,
	0xb5, 0x7c, 0x0e, 0xb3, 0xbe, 0x21, 0xec, 0x82, 0x02, 0x66, 0x13, 0x92, 0x2f, 0x60, 0xd1, 0xee,
	0xec, 0xde, 0x10, 0x76, 0xea, 0x9a, 0xdf, 0x34, 0x61, 0xfd, 0x19, 0xca, 0xaf, 0xd8, 0x0d, 0xfc,
	0x6a, 0xf7, 0xbb, 0x43, 0x4a, 0x2f, 0x1a, 0x81, 0x7c, 0x03, 0xe5, 0x21, 0x1e, 0xab, 0x7c, 0x59,
	0xac, 0xae, 0x3e, 0x2c, 0xd6, 0xfd, 0x76, 0x1d, 0xef, 0xd7, 0x23, 0xad, 0xff, 0x65, 0x20, 0x22,
	0x96, 0x37, 0x90, 0x5b, 0xc3, 0xda, 0xa2, 0xce, 0xad, 0x99, 0xf2, 0xe5, 0x17, 0xf9, 0x96, 0x70,
	0x65, 0xd0, 0xb7, 0x64, 0xfb, 0x60, 0x5d, 0x97, 0xd2, 0x5c, 0x52, 0xf1, 0x46, 0x4f, 0xb6, 0xc5,
	0xcd, 0xc1, 0x0d, 0x5d, 0x50, 0x82, 0xed, 0x2e, 0x29, 0xce, 0x32, 0x10, 0x61, 0xd7, 0xfe, 0x51,
	0x25, 0x1b, 0x4c, 0xf8, 0x1c, 0x61, 0x76, 0x19, 0x41, 0xc3, 0xdc, 0xb1, 0xbb, 0x57, 0xf3, 0x47,
	0x21, 0x4e, 0x07, 0x7a, 0x03, 0x62, 0x33, 0x84, 0x5d, 0x74, 0xef, 0xc9, 0x1d, 0xad, 0x99, 0xfa,
	0x30, 0x61, 0xf9, 0x1a, 0xc0, 0x23, 0x1d, 0x6d, 0x8b, 0x0f, 0xd6, 0xa4, 0x5c, 0x55, 0x62, 0xbe,
	0x18, 0x5d, 0x83, 0xf8, 0xe1, 0x91, 0xe4, 0x2b, 0x10, 0xcd, 0x10, 0x76, 0x2c, 0x4f, 0xdf, 0x8a,
	0xd6, 0x35, 0xb3, 0x4f, 0xb6, 0x45, 0xc1, 0xbc, 0x31, 0x86, 0xd0, 0xfb, 0xd4, 0x92, 0x13, 0xd4,
	0x3f, 0x41, 0xdc, 0xd9, 0x3d, 0x3e, 0xb9, 0x2c, 0x12, 0xc4, 0xc1, 0x9e, 0x9d, 0x62, 0x2d, 0x5f,
	0x42, 0xd5, 0x12, 0x36, 0x01, 0x1f, 0x9a, 0x90, 0xbc, 0x16, 0x23, 0xb1, 0x09, 0xa7, 0x1d, 0x12,
	0xd3, 0x0e, 0xe9, 0x4f, 0x00, 0xdf, 0xc9, 0x20, 0xdd, 0x59, 0xdc, 0xf3, 0xc4, 0xe2, 0x4c, 0xd3,
	0x0c, 0xb9, 0x8e, 0x1d, 0x6d, 0x79, 0x12, 0xf1, 0x2b, 0x65, 0x3d, 0x02, 0xfd, 0x1e, 0x4a, 0xd6,
	0xc9, 0xb7, 0x30, 0xfb, 0x15, 0xb5, 0x5e, 0x09, 0xee, 0xec, 0x4d, 0x4c, 0x7b, 0xb6, 0xac, 0xd3,
	0xe9, 0x76, 0xc6, 0x3f, 0xcd, 0xc7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x8e, 0x65, 0xdf,
	0x44, 0x03, 0x00, 0x00,
}
